# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: postgresql
  encoding: unicode
  database: lacala
  pool: 5
  timeout: 5000
  username: postgres
 

test:
  adapter: postgresql
  encoding: unicode
  database: lacala_test
  pool: 5
  timeout: 5000
  username: postgres


production:
  adapter: postgresql
  database: lacala_prod
  pool: 5
  timeout: 5000